name: easy_web_view
description: A super simple webview for Flutter Web and Mobile
version: 1.0.0+1
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/easy_web_view
issue_tracker: https://github.com/rodydavis/plugins/issues
maintainer: Rody Davis (@AppleEducate)
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.15+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
